---
- name: Ensure OpenSSH server is installed
  package:
     name: openssh-server
     state: present

- name: Create sshd_config backup
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.bak
    remote_src: yes
    backup: yes

- name: Configure SSH daemon
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart SSH service

- name: Ensure SSH service is running
  systemd:
     name: sshd
     enabled: yes
     state: started


